#include QMK_KEYBOARD_H

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

#define _QTY 0
#define _SYM 1
#define _NUM 2
#define _MVG 3
#define _NMP 4
#define _FNC 5
#define _FUT 6

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

[_QTY] = LAYOUT_planck_grid(
  RGUI_T(KC_TAB), KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_BSPC,
  LCTL_T(KC_ESC), KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOTE,
  KC_LSFT, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_DOT, KC_COMM, KC_SLSH, RSFT_T(KC_ENT),
  MO(_FNC), KC_LALT, KC_LGUI, MO(_MVG), MO(_SYM), KC_SPC, KC_SPC, MO(_NUM), OSM(MOD_HYPR), KC_RGUI, KC_RCTL, KC_NO),

[_SYM] = LAYOUT_planck_grid(
  KC_TILD, KC_EXLM, KC_AT, KC_HASH, KC_DLR, KC_PERC, KC_CIRC, KC_AMPR, KC_ASTR, KC_LPRN, KC_RPRN, KC_BSPC,
  KC_TRNS, KC_F1, KC_F2, KC_F3, KC_DEL, KC_NO, KC_MINS, KC_EQL, KC_PLUS, KC_LCBR, KC_RCBR, KC_PIPE,
  KC_LSFT, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, KC_UNDS, KC_NO, KC_BSLS, KC_LBRC, KC_RBRC, RSFT_T(KC_ENT),
  KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_GRAVE, LSFT(KC_COMM), LSFT(KC_DOT), KC_NO),

[_NUM] = LAYOUT_planck_grid(
  KC_GRV, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_BSPC,
  KC_NO, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_MINS, KC_EQL, KC_LCBR, KC_RCBR, KC_TRNS,
  KC_TRNS, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, KC_F12, KC_NO, KC_NUBS, KC_LBRC, KC_RBRC, KC_TRNS,
  KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, MO(_NMP), KC_TRNS, KC_TRNS, KC_TRNS, KC_NO, KC_COMM, KC_DOT, KC_TRNS),

[_MVG] = LAYOUT_planck_grid(
  KC_TRNS, KC_NO, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, LGUI(KC_C), KC_NO, KC_NO, KC_TRNS, LGUI(KC_V), KC_BSPACE,
  KC_TRNS, KC_TRNS, MO(6), KC_DEL, KC_NO, KC_NO, KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, KC_TRNS, KC_TRNS,
  KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_TRNS, LGUI(KC_SLSH), LGUI(KC_BSLS), KC_TRNS,
  KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),

[_NMP] = LAYOUT_planck_grid(
  KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_7, KC_8, KC_9, KC_MINUS, KC_BSPACE,
  KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_4, KC_5, KC_6, KC_PLUS, KC_ENTER,
  KC_LSHIFT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_1, KC_2, KC_3, KC_SLASH, KC_RSHIFT,
  KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_0, KC_DOT, KC_COMMA, KC_ASTR, KC_NO),

[_FNC] = LAYOUT_planck_grid(
  KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_MUTE, KC__VOLUP, KC_NO,
  KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC__VOLDOWN, KC_NO,
  KC_NO, RGB_TOG, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
  KC_NO, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO),

[_FUT] = LAYOUT_planck_grid(
  KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
  KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_WH_L, KC_WH_D, KC_WH_U, KC_WH_R, KC_NO, KC_NO,
  KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
  KC_NO, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO)
};


layer_state_t layer_state_set_user(layer_state_t state) {
    switch (get_highest_layer(state)) {
    case _SYM:
        rgblight_setrgb (0x00,  0x00, 0xFF);
        break;
    case _NUM:
        rgblight_setrgb (0xFF,  0x00, 0x00);
        break;
    case _MVG:
        rgblight_setrgb (0x00,  0xFF, 0x00);
        break;
    case _NMP:
        rgblight_setrgb (0x7A,  0x00, 0xFF);
        break;
    default: //  for any other layers, or the default layer
        rgblight_setrgb (0xD9,  0x1E, 0xDF);
        break;
    }
  return state;
}
